### ISSUE TITLE
auth script execution

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/pam_opnsense#2]
Currently our pam module executes `/usr/local/sbin/opnsense-auth`  as the user who tries to login, this should logically be root as the root user has access to the infrastructure underneath.

So far this hasn't been an issue, since our config.xml is world readable, which we are trying to solve on the road to 19.7.

**Comment by AdSchellevis** [comment]
https://github.com/opnsense/pam_opnsense/commit/4b3ac37fae7e2c9c182611545890a94e81136df7

**Comment by AdSchellevis** [comment]
needs a chmod+chown after installation, but further then that https://github.com/opnsense/pam_opnsense/commit/8840c93187d25176d70d8a8d7b17e8866bd6d72b adds the last missing glue.
```
chmod 4755 /usr/local/libexec/opnsense-pam
chown root  /usr/local/libexec/opnsense-pam
```

**Comment by fichtner** [comment]
https://github.com/opnsense/pam_opnsense/commit/fc2bb9ad3

**Comment by AdSchellevis** [comment]
@fichtner thanks!
